=== adgehbirhane/soap-web-service/XML/class_work/product.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="products">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="product" maxOccurs="unbounded">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="category">
								<xs:complexType>
									<xs:attribute name="id" type="xs:integer" use="required" />
								</xs:complexType>
							</xs:element>
							<xs:element name="name" type="xs:string" />
							<xs:element name="brand" type="xs:string" />
							<xs:element name="model_name" type="xs:string" />
							<xs:element name="screen_size" type="xs:string" />
							<xs:element name="color" type="xs:string" />
							<xs:element name="CPU_Model" type="xs:string" />
							<xs:element name="price" type="xs:integer" />
						</xs:sequence>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== adgehbirhane/soap-web-service/XML/class_work/product.xml
<?xml version="1.0" encoding="UTF-8"?>
<products xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="product.xsd">
	<product>
		<category id="1" />
		<name>
			HP
		</name>
		<brand>
			HP
		</brand>
		<model_name>
			hp laptop
		</model_name>
		<screen_size>
			15.6 inches
		</screen_size>
		<color>
			Silver
		</color>
		<CPU_Model>
			Core 9
		</CPU_Model>
		<price>
			50000
			<!-- category, product, customer, and order using .dtd and .xsd -->
		</price>
	</product>
	<product>
		<category id="2" />
		<name>
			Lenovo
		</name>
		<brand>
			Lenovo
		</brand>
		<model_name>
			Lenovo laptop
		</model_name>
		<screen_size>
			15.6 inches
		</screen_size>
		<color>
			Silver
		</color>
		<CPU_Model>
			Core 9
		</CPU_Model>
		<price>
			50000
		</price>
	</product>
</products>
