=== adgehbirhane/soap-web-service/XML/home_work/order.dtd
<!ELEMENT orders (order+)>
<!ELEMENT order (id, customer_id, product_id, quantity, order_date, status)>
<!ELEMENT id (#PCDATA)>
<!ELEMENT customer_id (#PCDATA)>
<!ELEMENT product_id (#PCDATA)>
<!ELEMENT quantity (#PCDATA)>
<!ELEMENT order_date (#PCDATA)>
<!ELEMENT status (#PCDATA)>
<!ATTLIST orders 
     xmlns:xsi CDATA #IMPLIED
     xsi:noNamespaceSchemaLocation CDATA #IMPLIED>

=== adgehbirhane/soap-web-service/XML/home_work/order.xml
<?xml version="1.0" encoding="UTF-8"?>  
<!-- <!DOCTYPE orders SYSTEM "order.dtd"> -->
<orders xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:noNamespaceSchemaLocation="order.xsd">
    <order>
        <id>1</id>
        <customer_id>1</customer_id>
        <product_id>1</product_id>
        <quantity>2</quantity>
        <order_date>2024-03-25</order_date>
        <status>Processing</status>
    </order>
    <order>
        <id>2</id>
        <customer_id>2</customer_id>
        <product_id>2</product_id>
        <quantity>1</quantity>
        <order_date>2024-03-24</order_date>
        <status>Shipped</status>
    </order>
    <order>
        <id>3</id>
        <customer_id>1</customer_id>
        <product_id>3</product_id>
        <quantity>1</quantity>
        <order_date>2024-03-26</order_date>
        <status>Delivered</status>
    </order>
    <order>
        <id>4</id>
        <customer_id>3</customer_id>
        <product_id>4</product_id>
        <quantity>3</quantity>
        <order_date>2024-03-27</order_date>
        <status>Processing</status>
    </order> 
</orders>
